# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJOZHbCAWCmHiPvtTZk5aQ1GCNkxIsD7
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

titanic = sns.load_dataset('titanic')

#What is the overall distribution of passengers across different classes (Pclass)?

titanic['pclass'].unique()

# as we see there are three pclass in the titanic dataset, i.e. 1, 2 and 3

titanic['pclass'].value_counts()

#as we seen . pclass 1 had 216 passenger, 2 class had 184,3 4991 passenger

sns.countplot(data = titanic, x ='pclass')
plt.title("passenger count by pclass")
plt.show()

#2. How is the age of passengers distributed?

sns.histplot(titanic['age'], kde = True, bins =40)
plt.title('Age Distribution')
plt.show()

# 3. 3. What is the distribution of passengers based on Sex?

titanic['sex'].unique()

titanic['sex'].value_counts()

sns.countplot(data =titanic, x ='sex')
plt.title("Gender Distribution")
plt.show()

#How many passengers embarked from each port (Embarked)?

titanic['embarked'].unique()

#emarked has null values(nan). i'll handel it later in FE

#lets check for the counts
titanic['embarked'].value_counts()

sns.countplot(data=titanic, x='embarked')
plt.title('Passenger Count by Embarkation Point')
plt.show()

#hat is the survival rate overall, and how does it vary by Pclass?

sns.barplot(data = titanic, x='pclass', y='survived')
plt.title("Survived rate by passenger class")
plt.show()

overall_survied_rate = titanic['survived'].mean()

print("overall survived rate :- ", overall_survied_rate)

survived_rate_by_pclass =titanic.groupby('pclass')['survived'].mean()

print("survived rate by p class :- ", survived_rate_by_pclass)

